stages:
  load_data:
    cmd: python3 src/load_data.py  --config=params.yaml
    deps:
    - src/load_data.py
    - src/get_data.py
    - data_source/WineQT.csv
    outs:
    - data/raw/WineQT.csv

  split_data:
    cmd: python3 src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/WineQT.csv
    outs:
    - data/processed/train_WineQT.csv
    - data/processed/test_WineQT.csv