stages:
  load_data:
    cmd: python3 src/load_data.py  --config=params.yaml
    deps:
    - src/load_data.py
    - src/get_data.py
    - data_source/WineQT.csv
    outs:
    - data/raw/WineQT.csv

  split_data:
    cmd: python3 src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/WineQT.csv
    outs:
    - data/processed/train_WineQT.csv
    - data/processed/test_WineQT.csv
  
  train_and_evaluate:
    cmd: python3 src/train_and_evaluate.py --config=params.yaml
    deps:
    - src/train_and_evaluate.py
    - data/processed/train_WineQT.csv
    - data/processed/test_WineQT.csv
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    
  log_production_model:
    cmd: python3 src/log_production_model.py --config=params.yaml
    deps: 
    - src/log_production_model.py