base:
  project:  winequality-project
  random_state: 34
  target_col: TARGET

data_source:
  gcp_source: data_source/WineQT.csv

load_data:
  raw_dataset_csv: data/raw/WineQT.csv

split_data:
  train_path: data/processed/train_WineQT.csv
  test_path: data/processed/test_WineQT.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.86
      l1_ratio: 0.81

model_dir: saved_models

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetTaxiModel
  remote_server_uri: http://0.0.0.0:2222


